In [60]:
import numpy as np
import torch
import torch.nn as nn

In [61]:
#Data preparation
data = np.genfromtxt(r'E:\AIO\PyTorch\Data\iris_2D_demo.csv', delimiter=',', skip_header=1)
x_data = torch.from_numpy(data[:, 0:2]).float()
y_data = torch.from_numpy(data[:, 2]).float()
print(x_data)
print(y_data)

tensor([[1.4000, 0.2000],
        [1.5000, 0.2000],
        [3.0000, 1.1000],
        [4.1000, 1.3000]])
tensor([0., 0., 1., 1.])


In [62]:
num_epoch = 1
N = len(y_data)
N

4

In [63]:
#Create a linear year
model = nn.Linear(2, 1)

#set value (for illustration)
model.weight.data = torch.Tensor([[0.5, -0.1]])
model.bias.data = torch.Tensor([0.1])

#print
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5000, -0.1000]], requires_grad=True)
Parameter containing:
tensor([0.1000], requires_grad=True)


In [64]:
loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),
                            lr=0.01)

In [65]:
#training
for epoch in range(num_epoch):
    for i in range(N):
        x = x_data[i]
        y = y_data[i:i+1]

        #y_hat
        y_hat = torch.sigmoid(model(x)) 
        print(f'y_hat: {y_hat.item()}')

        #loss
        loss = loss_fn(y_hat, y)
        print(f'loss: {loss.item()}')

        #compute gradient
        optimizer.zero_grad()
        loss.backward()
        print(f'(db, dw): ({model.bias.grad.data}, {model.weight.grad.data})')

        #update
        optimizer.step()
        print(f'(b, w): ({model.bias.data}, {model.weight.data})\n\n')

y_hat: 0.6856801509857178
loss: 1.1573442220687866
(db, dw): (tensor([0.6857]), tensor([[0.9600, 0.1371]]))
(b, w): (tensor([0.0931]), tensor([[ 0.4904, -0.1014]]))


y_hat: 0.6917833089828491
loss: 1.1769522428512573
(db, dw): (tensor([0.6918]), tensor([[1.0377, 0.1384]]))
(b, w): (tensor([0.0862]), tensor([[ 0.4800, -0.1028]]))


y_hat: 0.8042805790901184
loss: 0.2178070843219757
(db, dw): (tensor([-0.1957]), tensor([[-0.5872, -0.2153]]))
(b, w): (tensor([0.0882]), tensor([[ 0.4859, -0.1006]]))


y_hat: 0.8753998279571533
loss: 0.133074551820755
(db, dw): (tensor([-0.1246]), tensor([[-0.5109, -0.1620]]))
(b, w): (tensor([0.0894]), tensor([[ 0.4910, -0.0990]]))


