Create a tensor in PyTorch

In [ ]:
#From a list
import torch

a_data = [1, 2, 3]
a_data = torch.tensor(a_data)

print(a_data.shape)
print(a_data)

torch.Size([3])
tensor([1, 2, 3])


In [11]:
#From a Numpy Array
import numpy as np

b_data = np.array([1, 2, 3])
b_data = torch.from_numpy(b_data)

print(b_data.shape)
print(b_data)

torch.Size([3])
tensor([1, 2, 3], dtype=torch.int32)


In [12]:
#Create a tensor random
c_data = torch.rand(3, 3)
print(c_data)

tensor([[0.0973, 0.0856, 0.6719],
        [0.4411, 0.0134, 0.3112],
        [0.5052, 0.4575, 0.6294]])
